axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mainapp/', include('mainApp.urls', namespace='mainapp')),
    url(r'^userapp/', include('userApp.urls', namespace='userapp')),
    url(r'^orderapp/', include('orderApp.urls', namespace='orderapp')),
]

mainApp/urls.py
from django.conf.urls import url

from mainApp import views

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^market/', views.market, name='market'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^addCart/', views.addCart),
    url(r'^subCart/', views.subCart),
    url(r'^changeSingle/', views.changeSingle),
    url(r'^allSelect/', views.allSelect),
    url(r'^sub/', views.sub),
    url(r'^add/', views.add),
    url(r'^totalPrice', views.totalPrice)

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">


    {% block ext_css %}

    {% endblock %}
</head>
<body>
{% block headers %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>


{% block ext_js %}

{% endblock %}

</body>
</html>

templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/main.css' %}">
{% endblock %}


{% block headers %}
    {{ block.super }}
    <header>
    </header>
{% endblock %}


{% block footer %}
    {{ block.super }}

    <footer>
        <a href="{% url 'mainapp:home' %}">
            <dl class="home">
                <dt >
                    <span></span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>

        <a href="{% url 'mainapp:market' %}">
            <dl class="market">
                <dt >
                    <span></span>
                </dt>
                <dd>闪购</dd>
            </dl>
        </a>

        <a href="{% url 'mainapp:cart' %}">
            <dl class="cart">
                <dt >
                    <span></span>
                </dt>
                <dd>购物车</dd>
            </dl>
        </a>

        <a href="{% url 'mainapp:mine' %}">
            <dl class="mine">
                <dt >
                    <span></span>
                </dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>

{% endblock %}

templates/base_order.html
{% extends 'base.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/main.css' %}">
{% endblock %}


{% block headers %}
    {{ block.super }}
    <header></header>
{% endblock %}

templates/base_user.html
{% extends 'base.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/main.css' %}">
{% endblock %}


{% block headers %}
    {{ block.super }}
    <header>
    </header>
{% endblock %}

