axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mainapp/', include('mainApp.urls', namespace='mainapp')),
    url(r'^userapp/', include('userApp.urls', namespace='userapp')),
    url(r'^orderapp/', include('orderApp.urls', namespace='orderapp')),
]

orderApp/models.py
from django.db import models

# Create your models here.
from mainApp.models import Goods
from userApp.models import User


class Order(models.Model):
    o_user = models.ForeignKey(User)
    o_creattime = models.DateTimeField(auto_now_add=True)
    o_totalprice = models.FloatField()

    class Meta:
        db_table = 'order'


class orderGoods(models.Model):
    og_order = models.ForeignKey(Order)
    og_goods = models.ForeignKey(Goods)
    og_goods_num = models.IntegerField()

    class Meta:
        db_table = 'order_goods'

templates/axf/order/order.html
{% extends 'base_order.html' %}

{% load static %}


{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/order/order.css' %}">
    <link rel="stylesheet" href="{% static 'axf/order/order_detail.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/order/order.js' %}"></script>
{% endblock %}

{% block title %}
    订单
{% endblock %}

{% block headers %}
    {{ block.super }}
    <header></header>
{% endblock %}

{% block content %}
    {{ block.super }}
     <div class="container">
        <h1>订单编号:{{ order.id }}</h1>
         {% for ordergoods in order.ordergoods_set.all %}
            <div class="menuList">
                <a href="">
                    <img src="/static{{ ordergoods.og_goods.productimg }}" alt="">
                    <p>{{ ordergoods.og_goods.productlongname }}</p>
                    <p class="presentPrice"></p>
                </a>
                <section>
                    <span>{{ ordergoods.og_goods_num }}</span>
                </section>
            </div>
         {% endfor %}
        <div class="total_price" style="font-size: 0.4rem">
            总价:
            <span id="total_price" style="font-size: 0.4rem">{{ order.o_totalprice }}</span>
            </div>
        <button class="btn btn-block btn-success" style="font-size: 50px">支付</button>
    </div>
{% endblock %}